name: main workflow (test)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install PM2
        run: |
          npm install -g pm2

      - name: Install dependencies and run tests
        working-directory: ./frontend
        run: |
          npm i
          npm run build

      - name: Start Backend Server
        working-directory: ./backend
        run: |
          pm2 start dist/server.js --name backend
          echo "Backend server started"

      - name: Wait for Backend to Start
        run: |
          for i in {1..10}; do
            curl -f http://localhost:3000/health && break || sleep 5;
          done
