name: main workflow (test)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and run tests
        working-directory: ./frontend
        run: |
          npm i
          npm run build

      - name: Start Backend Server
        working-directory: ./backend
        run: |
          npm i
          node server.js
          
      - name: Sleep a bit so the server start
        run: |
          sleep 5

      - name: Check Backend
        run: |
          curl -f http://localhost:3000/api/v1 || exit 1
