name: main workflow (test)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and run tests
        working-directory: ./frontend
        run: |
          npm i
          npm run build
          
  build-and-push:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Log in to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
  
        - name: Build and push Frontend image
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }} ./frontend
            docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
  
        - name: Build and push Backend image
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }} ./backend
            docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy containers
        run: |
          docker ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
          docker ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}
          docker-compose up -d
