name: Test Branch Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Test Message
        run: echo "test"
